// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store/books.proto

package store

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	// global item UUID. used for purchases
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// name of the book
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// author of the book
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	// price of the book
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d23790b546a688, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ListBooksResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d23790b546a688, []int{1}
}

func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (m *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(m, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "store.Book")
	proto.RegisterType((*ListBooksResponse)(nil), "store.ListBooksResponse")
}

func init() {
	proto.RegisterFile("store/books.proto", fileDescriptor_38d23790b546a688)
}

var fileDescriptor_38d23790b546a688 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x71, 0x1b, 0x57, 0xea, 0x75, 0xea, 0x09, 0x55, 0x56, 0x59, 0x42, 0xa6, 0x4c, 0x8e,
	0x54, 0x24, 0x56, 0x24, 0x24, 0x24, 0x06, 0x26, 0xcf, 0x2c, 0x0d, 0x98, 0x12, 0x85, 0xe4, 0x2c,
	0xff, 0x19, 0xf8, 0xf6, 0xc8, 0xe7, 0xc0, 0xc2, 0x76, 0xf7, 0xf3, 0xf3, 0xbd, 0xf7, 0x60, 0x1f,
	0x22, 0x79, 0xdb, 0xf5, 0x44, 0x63, 0xd0, 0xce, 0x53, 0x24, 0x94, 0x8c, 0x8e, 0x37, 0x17, 0xa2,
	0xcb, 0x97, 0xed, 0x18, 0xf6, 0xe9, 0xa3, 0xb3, 0x93, 0x8b, 0xdf, 0x45, 0xd3, 0xbc, 0x42, 0xf5,
	0x48, 0x34, 0x22, 0x42, 0x95, 0xd2, 0xf0, 0xae, 0x44, 0x2d, 0xda, 0xad, 0xe1, 0x39, 0xb3, 0xf9,
	0x3c, 0x59, 0xb5, 0x2a, 0x2c, 0xcf, 0x78, 0x80, 0xcd, 0x39, 0xc5, 0x4f, 0xf2, 0x6a, 0xcd, 0x74,
	0xd9, 0xf0, 0x1a, 0xa4, 0xf3, 0xc3, 0x9b, 0x55, 0x55, 0x2d, 0xda, 0x95, 0x29, 0x4b, 0x73, 0x0f,
	0xfb, 0x97, 0x21, 0xc4, 0xec, 0x10, 0x8c, 0x0d, 0x8e, 0xe6, 0x60, 0xf1, 0x16, 0x24, 0xa7, 0x54,
	0xa2, 0x5e, 0xb7, 0xbb, 0xd3, 0x4e, 0x73, 0x4c, 0x9d, 0x45, 0xa6, 0xbc, 0x9c, 0x9e, 0x41, 0xf2,
	0x1f, 0x7c, 0x80, 0xed, 0xdf, 0x01, 0x3c, 0xe8, 0xd2, 0x44, 0xff, 0x36, 0xd1, 0x4f, 0xb9, 0xc9,
	0x51, 0x2d, 0x17, 0xfe, 0x59, 0x35, 0x57, 0xfd, 0x86, 0xb5, 0x77, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xab, 0x58, 0x08, 0xa3, 0x1f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BooksClient is the client API for Books service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BooksClient interface {
	ListBooks(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListBooksResponse, error)
}

type booksClient struct {
	cc grpc.ClientConnInterface
}

func NewBooksClient(cc grpc.ClientConnInterface) BooksClient {
	return &booksClient{cc}
}

func (c *booksClient) ListBooks(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListBooksResponse, error) {
	out := new(ListBooksResponse)
	err := c.cc.Invoke(ctx, "/store.Books/ListBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BooksServer is the server API for Books service.
type BooksServer interface {
	ListBooks(context.Context, *empty.Empty) (*ListBooksResponse, error)
}

// UnimplementedBooksServer can be embedded to have forward compatible implementations.
type UnimplementedBooksServer struct {
}

func (*UnimplementedBooksServer) ListBooks(ctx context.Context, req *empty.Empty) (*ListBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}

func RegisterBooksServer(s *grpc.Server, srv BooksServer) {
	s.RegisterService(&_Books_serviceDesc, srv)
}

func _Books_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Books/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServer).ListBooks(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Books_serviceDesc = grpc.ServiceDesc{
	ServiceName: "store.Books",
	HandlerType: (*BooksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBooks",
			Handler:    _Books_ListBooks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store/books.proto",
}
